/*
 * Copyright (c) 2025 Aerlync Labs Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_MUX_LPC84X_SWM_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_MUX_LPC84X_SWM_H_

/* Movable function selectors */
#define LPC84X_SWM_FUNC_USART0_TXD  0U
#define LPC84X_SWM_FUNC_USART0_RXD  1U
#define LPC84X_SWM_FUNC_USART0_RTS  2U
#define LPC84X_SWM_FUNC_USART0_CTS  3U
#define LPC84X_SWM_FUNC_USART0_SCLK 4U
#define LPC84X_SWM_FUNC_USART1_TXD  5U
#define LPC84X_SWM_FUNC_USART1_RXD  6U
#define LPC84X_SWM_FUNC_USART1_RTS  7U
#define LPC84X_SWM_FUNC_USART1_CTS  8U
#define LPC84X_SWM_FUNC_USART1_SCLK 9U
#define LPC84X_SWM_FUNC_USART2_TXD  10U
#define LPC84X_SWM_FUNC_USART2_RXD  11U
#define LPC84X_SWM_FUNC_USART2_RTS  12U
#define LPC84X_SWM_FUNC_USART2_CTS  13U
#define LPC84X_SWM_FUNC_USART2_SCLK 14U
#define LPC84X_SWM_FUNC_USART3_TXD  47U
#define LPC84X_SWM_FUNC_USART3_RXD  48U
#define LPC84X_SWM_FUNC_USART3_SCLK 49U
#define LPC84X_SWM_FUNC_USART4_TXD  50U
#define LPC84X_SWM_FUNC_USART4_RXD  51U
#define LPC84X_SWM_FUNC_USART4_SCLK 52U

/* Helper macro to encode a port/pin selection */
#define LPC84X_SWM_PORTPIN(port, pin) (((port) * 32U) + (pin))

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_MUX_LPC84X_SWM_H_ */
